<?php

namespace Cai\WebBundle\Repository;

/**
 * ImagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
