<?php

namespace Cai\WebBundle\Repository;

/**
 * ElementoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementoRepository extends \Doctrine\ORM\EntityRepository
{
}
