<?php

namespace Cai\WebBundle\Repository;

/**
 * SeguimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeguimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
