<?php

namespace Cai\WebBundle\Repository;

/**
 * TipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRepository extends \Doctrine\ORM\EntityRepository
{
}
