contacto_index:
    path:     /
    defaults: { _controller: "CaiWebBundle:Contacto:index" }
    methods:  GET
contacto_edit:
    path:     /edit
    defaults: { _controller: "CaiWebBundle:Contacto:edit" }
    methods:  [GET, POST]