seguimiento_index:
    path:     /
    defaults: { _controller: CaiWebBundle:Seguimiento:index }
seguimiento_entradas:
    path:     /entradas
    defaults: { _controller: CaiWebBundle:Seguimiento:entradas }

seguimiento_paginas:
    path:     /paginas
    defaults: { _controller: CaiWebBundle:Seguimiento:paginas }