slide_index:
    path:     /
    defaults: { _controller: "CaiWebBundle:Slide:index" }
    methods:  GET

slide_show:
    path:     /{id}/show
    defaults: { _controller: "CaiWebBundle:Slide:show" }
    methods:  GET

slide_new:
    path:     /new
    defaults: { _controller: "CaiWebBundle:Slide:new" }
    methods:  [GET, POST]

slide_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaiWebBundle:Slide:edit" }
    methods:  [GET, POST]

slide_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaiWebBundle:Slide:delete" }
    methods:  DELETE
