tipo_index:
    path:     /
    defaults: { _controller: "CaiWebBundle:Tipo:index" }
    methods:  GET

tipo_show:
    path:     /{id}/show
    defaults: { _controller: "CaiWebBundle:Tipo:show" }
    methods:  GET

tipo_new:
    path:     /new
    defaults: { _controller: "CaiWebBundle:Tipo:new" }
    methods:  [GET, POST]

tipo_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaiWebBundle:Tipo:edit" }
    methods:  [GET, POST]

tipo_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaiWebBundle:Tipo:delete" }
    methods:  DELETE
