<?php

namespace Cai\ClubesBundle\Repository;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAprobados(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT club
                FROM CaiClubesBundle:Club club
                WHERE club.aprobado = true'
            )->getResult();
    }
}
