cai_comunicaciones_material:
    resource: "@CaiComunicacionesBundle/Resources/config/routing/material.yml"
    prefix:   /material

cai_comunicaciones_solicitudes:
    resource: "@CaiComunicacionesBundle/Resources/config/routing/solicitud.yml"
    prefix:   /