club_index:
    path:     /
    defaults: { _controller: "CaiClubesBundle:Club:index" }
    methods:  GET

club_show:
    path:     /{id}/show
    defaults: { _controller: "CaiClubesBundle:Club:show" }
    methods:  GET

club_new:
    path:     /new
    defaults: { _controller: "CaiClubesBundle:Club:new" }
    methods:  [GET, POST]

club_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaiClubesBundle:Club:edit" }
    methods:  [GET, POST]

club_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaiClubesBundle:Club:delete" }
    methods:  DELETE

club_cambiar_estado:
    path:     /{id}/estado
    defaults: { _controller: CaiClubesBundle:Club:estado}