cai_web:
    resource: "@CaiWebBundle/Resources/config/routing.yml"
    prefix:   /backend

cai_frontend:
    resource: "@CaiFrontendBundle/Resources/config/routing.yml"
    prefix:   /

gulloa_security:
    resource: "@GulloaSecurityBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
