cai_reclamos:
    resource: "@CaiReclamosBundle/Resources/config/routing.yml"
    prefix:   /backend/reclamos

gulloa_security:
    resource: "@GulloaSecurityBundle/Resources/config/routing.yml"
    prefix:   /
cai_web:
    resource: "@CaiWebBundle/Resources/config/routing.yml"
    prefix:   /backend
cai_clubes:
    resource: "@CaiClubesBundle/Resources/config/routing.yml"
    prefix:   /backend/clubes

cai_frontend:
    resource: "@CaiFrontendBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
