# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_SUPER_ADMIN:   ROLE_ADMIN
        ROLE_ADMIN:   [ 'ROLE_DIRECTIVA', 'ROLE_PROYECTOS', 'ROLE_COMUNIDAD']
        ROLE_DIRECTIVA: ROLE_JEFE_DE_COMISION
        ROLE_JEFE_DE_COMISION: ROLE_USER

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory,users_provider]
        users_provider:
            entity:
                class: GulloaSecurityBundle:User
                property: username
        in_memory:
            memory:
                users:
                    root:
                        password: '%root_password%'
                        roles: 'ROLE_SUPER_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Gulloa\SecurityBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            form_login:
                login_path:           /login
                check_path:           /login_check
                default_target_path:  default_target
            logout:
                path:   /logout
                target: /login
            remember_me:
                secret:   '%secret%'
                path:     /
            anonymous: ~
        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/backend/role, roles: ROLE_SUPER_ADMIN }
        - { path: ^/backend/user, roles: ROLE_ADMIN }
        - { path: ^/backend/reclamos, roles: ROLE_COMUNIDAD }
        - { path: ^/backend/clubes, roles: ROLE_PROYECTOS }
        - { path: ^/backend/categoria, roles: ROLE_ADMIN }
        - { path: ^/backend/menu, roles: ROLE_DIRECTIVA }
        - { path: ^/backend/tipo, roles: ROLE_DIRECTIVA }
        - { path: ^/backend/menu, roles: ROLE_DIRECTIVA }
        - { path: ^/backend/persona, roles: ROLE_DIRECTIVA }
        - { path: ^/backend/slider, roles: ROLE_DIRECTIVA }
        - { path: ^/backend/menu, roles: ROLE_DIRECTIVA }
        - { path: ^/backend/contacto, roles: ROLE_DIRECTIVA }
        - { path: ^/backend, roles: ROLE_JEFE_DE_COMISION }

        - { path: ^/perfil, roles: ROLE_USER }
        - { path: ^/clubes/crear, roles: ROLE_USER }

        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }