frontend_clubes:
    path:     /
    defaults: { _controller: CaiFrontendBundle:Club:index }
frontend_clubes_new:
    path:     /crear
    defaults: { _controller: CaiFrontendBundle:Club:new }
frontend_clubes_show:
    path:     /{slug}
    defaults: { _controller: CaiFrontendBundle:Club:show }

