recover_password:
    path:     /recover
    defaults: { _controller: CaiFrontendBundle:Registro:recover }
recover_error:
    path:     /recover/not/{token}
    defaults: { _controller: CaiFrontendBundle:Registro:recoverNot }

change_password:
    path:     /cambiar/{token}
    defaults: { _controller: CaiFrontendBundle:Registro:change }