profile:
    path:     /
    defaults: { _controller: CaiFrontendBundle:Profile:myProfile }

profile_change_password:
    path:     /cambiar/password
    defaults: { _controller: CaiFrontendBundle:Profile:changePassword }