services:
    api.eventos:
        class: Cai\ApiBundle\ServicesClass\ServiceEventos
        arguments: ["@doctrine.orm.entity_manager", "@api.auth"]
    api.auth:
        class: Cai\ApiBundle\ServicesClass\ServiceAuth
        arguments: ["@doctrine.orm.entity_manager"]