cai_frontend_password:
    resource: "@CaiFrontendBundle/Resources/config/routing/password.yml"
    prefix:   /password

cai_frontend_registro:
    resource: "@CaiFrontendBundle/Resources/config/routing/registro.yml"
    prefix:   /registro

cai_frontend_homepage:
    path:     /
    defaults: { _controller: CaiFrontendBundle:Default:index }

cai_frontend_noticias:
    path:     /noticias
    defaults: { _controller: CaiFrontendBundle:Default:noticias }

cai_frontend_home:
    path:     /home
    defaults: { _controller: CaiFrontendBundle:Default:home }

cai_frontend_entrada:
    path:     /entrada/{slug}
    defaults: { _controller: CaiFrontendBundle:Default:entrada }

user_activation:
    path:     /activar/{token}
    defaults: { _controller: CaiFrontendBundle:Registro:activeUser }


