cai_frontend_clubes:
    resource: "@CaiFrontendBundle/Resources/config/routing/clubes.yml"
    prefix:   /clubes
cai_frontend_profile:
    resource: "@CaiFrontendBundle/Resources/config/routing/profile.yml"
    prefix:   /perfil
cai_frontend_passord:
    resource: "@CaiFrontendBundle/Resources/config/routing/password.yml"
    prefix:   /password
cai_frontend_registro:
    resource: "@CaiFrontendBundle/Resources/config/routing/registro.yml"
    prefix:   /registro
cai_frontend_noticias:
    path:     /noticias/{categoria}
    defaults: { _controller: CaiFrontendBundle:Default:noticias, categoria: null }
cai_frontend_busqueda:
    path:     /buscar
    defaults: { _controller: CaiFrontendBundle:Default:buscar }
cai_frontend_home:
    path:     /home
    defaults: { _controller: CaiFrontendBundle:Default:home }
cai_frontend_entrada:
    path:     /entrada/{slug}
    defaults: { _controller: CaiFrontendBundle:Default:entrada }
user_activation:
    path:     /activar/{token}
    defaults: { _controller: CaiFrontendBundle:Registro:activeUser }
cai_frontend_api:
    resource: "@CaiFrontendBundle/Resources/config/routing/api.yml"
    prefix:   /api
cai_frontend_reclamos:
    path:     /buzon
    defaults: { _controller: CaiFrontendBundle:Reclamo:new }
cai_frontend_page:
    path:     /{slug}
    defaults: { _controller: CaiFrontendBundle:Default:pagina}
cai_frontend_homepage:
    path:     /
    defaults: { _controller: CaiFrontendBundle:Default:index }