cai_frontend_registro:
    resource: "@CaiFrontendBundle/Resources/config/routing/registro.yml"
    prefix:   /registro

cai_frontend_homepage:
    path:     /
    defaults: { _controller: CaiFrontendBundle:Default:index }

user_activation:
    path:     /activar/{token}
    defaults: { _controller: CaiFrontendBundle:Registro:activeUser }

recover_password:
    path:     /recover_password
    defaults: { _controller: CaiFrontendBundle:Registro:recover }
