cai_frontend_password:
    resource: "@CaiFrontendBundle/Resources/config/routing/password.yml"
    prefix:   /password

cai_frontend_registro:
    resource: "@CaiFrontendBundle/Resources/config/routing/registro.yml"
    prefix:   /registro

cai_frontend_homepage:
    path:     /
    defaults: { _controller: CaiFrontendBundle:Default:index }

cai_frontend_propuesta:
    path:     /{i}
    defaults: { _controller: CaiFrontendBundle:Default:propuesta }

user_activation:
    path:     /activar/{token}
    defaults: { _controller: CaiFrontendBundle:Registro:activeUser }


