services:
    cai_web.auxiliar:
       class: Cai\WebBundle\Utils\Auxiliar
       arguments: [ "@doctrine.orm.entity_manager", '@templating']
    cai_web.images:
       class: Cai\WebBundle\Utils\ImagesEditor
#    cai_web.example:
#        class: Cai\WebBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
