Cai\WebBundle\Entity\Contacto:
    type: entity
    table: null
    repositoryClass: Cai\WebBundle\Repository\ContactoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lema:
            type: string
            length: 255
        direccion:
            type: string
            length: 255
        telefono:
            type: string
            length: 255
        twitter:
            type: string
            length: 255
        facebook:
            type: string
            length: 255
        youtube:
            type: string
            length: 255
        mail:
            type: string
            length: 255
        descripcion:
            type: text
        vimeo:
            type: string
            length: 255
    lifecycleCallbacks: {  }
