Cai\WebBundle\Entity\Evento:
    type: entity
    table: null
    repositoryClass: Cai\WebBundle\Repository\EventoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        descripcion:
            type: text
        fecha:
            type: datetime
    lifecycleCallbacks: {  }
