Cai\WebBundle\Entity\Pagina:
    type: entity
    table: null
    repositoryClass: Cai\WebBundle\Repository\PaginaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titulo:
            type: string
            length: 255
        slug:
            type: string
            length: 255
            unique: true
        cuerpo:
            type: text
        fecha:
            type: datetime
    lifecycleCallbacks: {  }
