Cai\WebBundle\Entity\Persona:
    type: entity
    table: null
    repositoryClass: Cai\WebBundle\Repository\PersonaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        apellido:
            type: string
            length: 255
        cargo:
            type: string
            length: 255
        descripcion:
            type: text
        mail:
            type: string
            length: 255
        facebook:
            type: string
            length: 255
            nullable: true
        twitter:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
