Cai\WebBundle\Entity\Slide:
    type: entity
    table: null
    repositoryClass: Cai\WebBundle\Repository\SlideRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        posicion:
            type: integer
        path:
            type: string
            length: 255
    lifecycleCallbacks: {  }
